version: "3.8"
services:
  api:
    # image: thomas-oliver/nestjs-dockerized 
    build:
      dockerfile: Dockerfile
      context: .
      # Only will build development stage from our dockerfile
      target: development
    # Mount our host Directory to the docker container
    # Mount (.) current directory to the docker container thomas/src/app
    # reflect file changes from host to container
    volumes:
      - ./server:/var/www/simple-git/server
      - /var/www/simple-git/server/node_modules
    # Run in Debug Mode: npm run start:debug --> Don't forget to start your vscode debugger!
    # Run in dev Mode: npm run start:dev
    command: yarn start:dev
